### ISSUE TITLE
Help Cannot Run the code

### ISSUE THREAD

**Issue by Jumabek** [TomHeaven/AnomalyAnalysisWithOpticalFlow#1]
Hi @TomHeaven ,
Thanks for the code,
I am reading your paper and I am curious to run the code and play with it.
After setting up opencv paths in Property page, I still cannot run the code. It just exits without any error.
Any idea what is going on.

Plus, is there any documentation on this code that you can share with other than the paper itself. Because I found the comments non-readable.

Thanks!

![image](https://user-images.githubusercontent.com/4343873/26908473-abf18f80-4baf-11e7-9838-39ca0a3dacf3.png)

**Comment by TomHeaven** [comment]
Thanks for your interest in our work. I have updated README.md and explain the usage. You need to pass parameters to the program. For example:

```
AnomalyAnalysisWithOpticalFlow.exe E:\videos train.avi test.avi
```

**Comment by Jumabek** [comment]
Thank you so much, I appreciate your efforts!
