### ISSUE TITLE
Help running the code

### ISSUE THREAD

**Issue by logiti** [TomHeaven/AnomalyAnalysisWithOpticalFlow#4]
"You need to configure local OpenCV path to compile the project"
What does that mean? And how do I use that?

Thanks

**Comment by TomHeaven** [comment]
Hi, you are expected to ask the question on stackoverflow or opencv forum since they are basic knowledges for C++.

**Comment by PrincyX** [comment]
I did (a couple months ago) and no one answered
https://stackoverflow.com/questions/55895398/how-do-i-configure-local-opencv-path-to-compile-a-project
